### Create Comment
POST http://localhost:8080/comment
Content-Type: application/json

{
  "content": "4st",
  "userId": 1,
  "postId": 1
}

### Get Comment
GET http://localhost:8080/comment?postId=1
Content-Type: application/json