frontend:
  url: http://localhost:3000
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config.import: optional:file:.env[.properties]
  datasource:
    #    url: jdbc:h2:tcp://localhost:1521/ciazza
    url: jdbc:mysql://localhost:3306/ciazza_kotlin
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace