### Create Educator
POST http://localhost:8080/educator
Content-Type: application/json

{
  "name": "Bob"
}

### Get Educator List
GET http://localhost:8080/educator

### Get Educator
GET http://localhost:8080/educator/1

