### Create Student
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "faker"
}

### Get Student List
GET http://localhost:8080/student

### Get Student
GET http://localhost:8080/student/8

### Get Lecture of student
GET http://localhost:8080/student/8/lectures?semester=SPRING_2024